"""
VOIDSIGNAL Phase 12 — Multi-omics integration engine.
"""

from voidsignal.omics.bridge import (
    MultiOmicsBridge,
    MultiOmicsProfile,
    OmicsBridgeResult,
    make_demo_multiomics_profile,
)
from voidsignal.omics.epigenomics import (
    ChromatinAccessibilityRecord,
    EpigenomicProfile,
    EpigenomicTransformer,
    HistoneAcetylationRecord,
    MethylationRecord,
    TranscriptionScale,
    acetylation_factor,
    accessibility_factor,
    make_demo_epigenomic_profile,
    methylation_factor,
)
from voidsignal.omics.metabolomics import (
    FBAResult,
    MetabolicCoupler,
    MetabolicCoupling,
    MetabolicFeedbackState,
    MetabolicNetwork,
    MetabolicReaction,
    Metabolite,
    MetabolomicProfile,
    build_core_energy_network,
    make_demo_metabolomic_profile,
    michaelis_menten_multiplier,
    solve_fba,
)
from voidsignal.omics.proteomics import (
    ProteinActivityState,
    PTMKind,
    PTMProfile,
    PTMSite,
    PTMTransformer,
    aggregate_ptm_state,
    make_demo_ptm_profile,
)
from voidsignal.omics.splicing import (
    IsoformKineticEffect,
    IsoformRecord,
    SplicingProfile,
    SplicingTransformer,
    aggregate_psi,
    make_demo_splicing_profile,
    parse_psi_matrix,
)

__all__ = [
    "ChromatinAccessibilityRecord",
    "EpigenomicProfile",
    "EpigenomicTransformer",
    "FBAResult",
    "HistoneAcetylationRecord",
    "IsoformKineticEffect",
    "IsoformRecord",
    "MetabolicCoupler",
    "MetabolicCoupling",
    "MetabolicFeedbackState",
    "MetabolicNetwork",
    "MetabolicReaction",
    "Metabolite",
    "MetabolomicProfile",
    "MethylationRecord",
    "MultiOmicsBridge",
    "MultiOmicsProfile",
    "OmicsBridgeResult",
    "PTMKind",
    "PTMProfile",
    "PTMSite",
    "PTMTransformer",
    "ProteinActivityState",
    "SplicingProfile",
    "SplicingTransformer",
    "TranscriptionScale",
    "acetylation_factor",
    "accessibility_factor",
    "aggregate_psi",
    "aggregate_ptm_state",
    "build_core_energy_network",
    "make_demo_epigenomic_profile",
    "make_demo_metabolomic_profile",
    "make_demo_multiomics_profile",
    "make_demo_ptm_profile",
    "make_demo_splicing_profile",
    "methylation_factor",
    "michaelis_menten_multiplier",
    "parse_psi_matrix",
    "solve_fba",
]
