"""
CISTRON UX layer — plain-language translation, progressive disclosure,
visual pathway canvas exporters, and studio encyclopedia/causal payloads.
"""

from cistron.ui.studio_cards import (
    build_causal_payload,
    crosstalk_viewport_payload,
    demo_rich_mapk_entities,
    encyclopedia_card_for,
    network_encyclopedia_index,
)
from cistron.ui.translator import (
    METRIC_CATALOG,
    BadgeTone,
    ExecutiveSummary,
    MetricDefinition,
    MetricTranslator,
    TranslatedMetric,
    annotate_abbreviations,
    build_executive_summary,
    compose_progressive_brief,
    get_human_context,
    normalize_metric_key,
    translate_metric,
    translate_metrics,
    wrap_raw_telemetry,
    DEFAULT_TRANSLATOR,
)
from cistron.ui.visual_translator import (
    VISUAL_LEGEND,
    EdgeVisual,
    EdgeVisualState,
    MicroenvironmentVisual,
    NodeVisual,
    NodeVisualState,
    VisualFrame,
    VisualPathwayTranslator,
    VisualTimeline,
    VisualTranslatorConfig,
    apply_drug_block_visual,
    apply_knockout_visual,
    build_tme_visual,
    classify_node_activity,
    flux_to_pulse_speed,
    flux_to_thickness,
    make_demo_visual_timeline,
)

__all__ = [
    "DEFAULT_TRANSLATOR",
    "METRIC_CATALOG",
    "VISUAL_LEGEND",
    "BadgeTone",
    "EdgeVisual",
    "EdgeVisualState",
    "ExecutiveSummary",
    "MetricDefinition",
    "MetricTranslator",
    "MicroenvironmentVisual",
    "NodeVisual",
    "NodeVisualState",
    "TranslatedMetric",
    "VisualFrame",
    "VisualPathwayTranslator",
    "VisualTimeline",
    "VisualTranslatorConfig",
    "annotate_abbreviations",
    "apply_drug_block_visual",
    "apply_knockout_visual",
    "build_causal_payload",
    "build_executive_summary",
    "build_tme_visual",
    "classify_node_activity",
    "compose_progressive_brief",
    "crosstalk_viewport_payload",
    "demo_rich_mapk_entities",
    "encyclopedia_card_for",
    "flux_to_pulse_speed",
    "flux_to_thickness",
    "get_human_context",
    "make_demo_visual_timeline",
    "network_encyclopedia_index",
    "normalize_metric_key",
    "translate_metric",
    "translate_metrics",
    "wrap_raw_telemetry",
]
